Moving to subdir - Linux add edge node
Azure/azure-quickstart-templates pull request #11241
Opened 2021-06-16 22:13 UTC by guyhay

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-06-16 22:52 UTC, bmoore-msft commented
Let's copy - not move, I promise Jonathan we wouldn't do any more outright moves.

2021-06-18 15:15 UTC, bmoore-msft requested changes

2021-06-18 15:15 UTC, bmoore-msft commented on quickstarts/microsoft.hdinsight/101-hdinsight-linux-add-edge-node/azuredeploy.json
> +      "defaultValue": "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-hdinsight-linux-add-edge-node",
change the defaultValue to ```[deployment().properties.templateLink.uri]```

2021-06-18 15:15 UTC, bmoore-msft commented on quickstarts/microsoft.hdinsight/101-hdinsight-linux-add-edge-node/azuredeploy.json
> +            "uri": "[concat(parameters('_artifactsLocation'), parameters('installScriptActionFolder'), '/', parameters('installScriptAction'), parameters('_artifactsLocationSasToken'))]",
use: 
```[uri(parameters('_artifactsLocation'), concat(parameters('installScriptActionFolder'), '/', parameters('installScriptAction'), parameters('_artifactsLocationSasToken')))]```

2021-06-18 17:49 UTC, guyhay commented
fixed in another branch https://github.com/Azure/azure-quickstart-templates/pull/10747#event-4853943485

2021-06-18 17:49 UTC, closed without merging