FIX-BESTPRACTICES: drone-ubuntu-vm
Azure/azure-quickstart-templates pull request #11448
Opened 2021-06-25 16:05 UTC by akhilthomas011

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-07-06 15:39 UTC, bmoore-msft requested changes

2021-07-06 15:39 UTC, bmoore-msft commented on application-workloads/drone/drone-ubuntu-vm/azuredeploy.json
> +        "description": "Username assigned to new local user on VM"
update description

2021-07-06 15:39 UTC, bmoore-msft commented on application-workloads/drone/drone-ubuntu-vm/azuredeploy.json
> +      "defaultValue": "Standard_A3",
use the v2 series for the defaultValue

2021-07-08 07:49 UTC, badri-spektra commented on application-workloads/drone/drone-ubuntu-vm/azuredeploy.json
> +        "description": "Username assigned to new local user on VM"
updated

2021-07-08 07:50 UTC, badri-spektra commented on application-workloads/drone/drone-ubuntu-vm/azuredeploy.json
> +      "defaultValue": "Standard_A3",
changed to v2 series

2021-07-13 14:07 UTC, merged