Added bicep file to create Device Update account
Azure/azure-quickstart-templates pull request #11693
Opened 2021-07-23 22:29 UTC by abatishchev

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added bicep file to create Device Update account

2021-07-26 14:48 UTC, bmoore-msft requested changes
Also check the pipeline results - it's saying your json and bicep don't match.

2021-07-26 14:48 UTC, bmoore-msft commented on quickstarts/microsoft.deviceupdate/deviceupdate-create-account/main.bicep
> +resource accountName_resource 'Microsoft.DeviceUpdate/accounts@2020-03-01-preview' = {
remove the _resource from the symbolic name - can probably just use "account" (since you'll need to disambiguate)

2021-07-26 18:03 UTC, abatishchev commented
@bmoore-msft done! The CI pipeline is green now.

2021-07-26 19:00 UTC, bmoore-msft commented
Did you remove the metadata property from azuredeploy.json?

2021-08-02 17:22 UTC, abatishchev commented
@bmoore-msft sorry, been on vacation out of state without internet. I indeed accidentally deleted the bicep metadata. Added it back, running CI now.

2021-08-02 19:34 UTC, merged