FIX-BESTPRACTICES: vm-custom-script-windows
Azure/azure-quickstart-templates pull request #11694
Opened 2021-07-26 08:35 UTC by badri-spektra

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-07-26 14:45 UTC, bmoore-msft requested changes

2021-07-26 14:45 UTC, bmoore-msft commented on quickstarts/microsoft.compute/vm-custom-script-windows/azuredeploy.json
> -      "defaultValue": "[deployment().properties.templateLink.uri]"
revert this change

2021-07-26 14:45 UTC, bmoore-msft commented on quickstarts/microsoft.compute/vm-custom-script-windows/azuredeploy.json
>      "scriptFileName": "Copy-FileFromAzure.ps1",
revert this change and move the files back to the root

2021-07-26 15:46 UTC, badri-spektra commented
@bmoore-msft there are two templates with names "list-storage-keys-windows-vm" and "vm-custom-script-windows", if we update artifacts location of these two templates main template is getting failed. these two templates are working only if we use absolute path in artifacts location

PR numbers 11664 & 11694

2021-08-16 16:08 UTC, bmoore-msft commented
fixed in a later PR

2021-08-16 16:08 UTC, closed without merging