IBM Cloudpak for data 4.0 Changes
Azure/azure-quickstart-templates pull request #11695
Opened 2021-07-26 18:11 UTC by muthukumarbala07

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added changes from the cloudpak for data 4.0 version
* Fix for yum install issue on the NFS server.

2021-07-27 13:45 UTC, bmoore-msft requested changes
Manual deployment failed, I can give you access to the RG if you want to debug - email me the account to use.

Also, check the pipeline for BP violations that need to be fixed.

2021-07-28 17:52 UTC, muthukumarbala07 commented on application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/azuredeploy.parameters.json
> +            "value": "ttk-gen-artifacts"
Review comments addressed. Changed the value to GEN-UNIQUE

2021-07-28 17:53 UTC, muthukumarbala07 commented on application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/scripts/deployCloudPakLite.sh
> +runuser -l $SUDOUSER -c "wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O  $CPDTEMPLATES/jq"
Removed personal repo and using org repo rpm to install jq.

2021-07-29 13:01 UTC, muthukumarbala07 commented
Hi @bmoore-msft, I have made the changes and made a commit. I've emailed you my azure account details as well. Can give access to the RG where manual deployment is failing. 

Thanks, 
Muthukumar.

2021-08-05 14:41 UTC, bmoore-msft requested changes

2021-08-05 14:41 UTC, bmoore-msft commented on application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/azuredeploy.json
> +		"networkReadNonAction": "",
remove empty property

2021-08-05 18:41 UTC, muthukumarbala07 commented on application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/azuredeploy.json
> +		"networkReadNonAction": "",
Removed the empty property.

2021-08-05 18:44 UTC, muthukumarbala07 commented on application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/azuredeploy.json
> +			"id": "[resourceId(resourceGroup().name, 'Microsoft.Network/publicIPAddresses', variables('bastionPublicIpDnsLabel'))]"
Removed resourceGroup().name from resourceId() function.

2021-08-05 18:59 UTC, muthukumarbala07 commented
Hi Brian, all the BP violations have been addressed and rectified.

2021-08-05 19:20 UTC, merged