New from bicep example: 101/function-http-trigger
Azure/azure-quickstart-templates pull request #11759
Opened 2021-08-03 02:19 UTC by StephenWeatherford

Created a new QuickStart sample from the bicep example in https://github.com/Azure/bicep/tree/main/docs/examples/101/function-http-trigger

See the contribution guide here: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

2021-08-12 19:23 UTC, MarcusFelling commented
Experiencing diff bug for loadTextContent

https://dev.azure.com/azurequickstarts/azure-quickstart-templates/_build/results?buildId=79821&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=499ce139-2b14-5970-20c3-793870720d06&l=240

2021-08-25 14:09 UTC, bmoore-msft requested changes

2021-08-25 14:09 UTC, bmoore-msft commented on quickstarts/microsoft.web/function-http-trigger/README.md
> +# TODO: Create ReadMe
fix title

2021-08-25 15:21 UTC, MarcusFelling commented on quickstarts/microsoft.web/function-http-trigger/README.md
> +# TODO: Create ReadMe
Good catch. Fixed.

2021-09-08 13:56 UTC, merged