add bicep for data-share-share-storage-account
Azure/azure-quickstart-templates pull request #12012
Opened 2021-11-08 20:29 UTC by jbpaux

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add bicep for data-share-share-storage-account
* Bump API versions
* Remove unusable parameters and simplify template

2021-11-08 20:32 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2021-11-08 20:47 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2021-11-11 19:25 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2021-11-12 16:08 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2021-11-12 16:12 UTC, bmoore-msft requested changes

2021-11-12 16:12 UTC, bmoore-msft commented on quickstarts/microsoft.datashare/data-share-share-storage-account/main.bicep
> +var roleAssignmentName = guid(uniqueString(storageAccountName, storageBlobDataReaderRoleDefinitionId, dataShareAccountName))
use:
```
guid(sa.id, storageBlobDataReaderRoleDefinitionId, dataShareAccount.id)
```

2021-11-12 16:12 UTC, bmoore-msft commented on quickstarts/microsoft.datashare/data-share-share-storage-account/main.bicep
> +    principalId: dataShareAccount.identity.principalId
add:
```
principalType: 'ServicePrincipal'
```

2021-11-12 16:12 UTC, bmoore-msft commented on quickstarts/microsoft.datashare/data-share-share-storage-account/main.bicep
> +  dependsOn: [
remove all the dependsOn for the roleAssignment - I don't think it's necessary since the template is working and the RA is likely not replicated.

2021-11-13 10:47 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2021-11-17 21:52 UTC, jbpaux commented
not sure why it failed in us gov, maybe assignement propagation but anyway should be good

2021-11-17 23:07 UTC, bmoore-msft commented
/azp run

2021-11-17 23:11 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2021-11-29 22:38 UTC, jbpaux commented
Not sure why it's failing in us gov while it shouldn't :(

2022-01-24 16:28 UTC, bmoore-msft commented
/azp run

2022-01-31 10:41 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-02-15 16:38 UTC, azure-quickstarts commented
@mumian - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-02-16 10:28 UTC, jbpaux commented
Oh thank you @bmoore-msft I was going crazy on this one.

2022-02-16 15:53 UTC, bmoore-msft commented
It's a hack, so not garaunteed to work, but it should help...

2022-02-16 15:53 UTC, merged