readme file is change
Azure/azure-quickstart-templates pull request #12164
Opened 2022-02-09 16:33 UTC by RaghavaIT

it is not related to standard code instruction

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-02-09 16:34 UTC, RaghavaIT commented
changes done

2022-02-09 16:34 UTC, RaghavaIT commented
change done

2022-02-15 17:55 UTC, bmoore-msft requested changes

2022-02-15 17:55 UTC, bmoore-msft commented on README.md
> +## this is module for test purpose
This is a header - what is the text needed below the header?

2022-04-12 20:03 UTC, bmoore-msft commented
Closing abandoned request - please reopen if you can address the feedback.

2022-04-12 20:03 UTC, closed without merging