0308 erin automation
Azure/azure-quickstart-templates pull request #12267
Opened 2022-03-08 20:40 UTC by mumian

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-03-08 20:44 UTC, azure-quickstarts commented
@MGoedtel - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-03-08 21:14 UTC, azure-quickstarts commented
@MGoedtel - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-03-17 20:35 UTC, azure-quickstarts commented
@MGoedtel - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-12 20:12 UTC, bmoore-msft commented
/azp run

2022-04-12 20:15 UTC, azure-quickstarts commented
@MGoedtel - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-12 20:36 UTC, bmoore-msft requested changes

2022-04-12 20:36 UTC, bmoore-msft commented on quickstarts/microsoft.automation/101-automation/main.bicep
> +param artifactsLocation string = deployment().properties.templateLink.uri
this needs to start with an underscore as in the original template

2022-04-12 20:36 UTC, bmoore-msft commented on quickstarts/microsoft.automation/101-automation/main.bicep
> +param artifactsLocationSasToken string = ''
this needs to start with an underscore as in the original template

2022-04-13 15:34 UTC, azure-quickstarts commented
@MGoedtel - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-06-10 17:04 UTC, azure-quickstarts commented
@MGoedtel - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-06-28 16:46 UTC, closed without merging