update api versions and create bicep file
Azure/azure-quickstart-templates pull request #12275
Opened 2022-03-09 21:00 UTC by mumian

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-03-09 21:04 UTC, azure-quickstarts commented
@ju-shim - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-12 20:12 UTC, bmoore-msft commented
/azp run

2022-04-12 20:16 UTC, azure-quickstarts commented
@ju-shim - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-12 20:37 UTC, bmoore-msft requested changes

2022-04-12 20:37 UTC, bmoore-msft commented on demos/vmss-windows-webapp-dsc-autoscale/main.bicep
> +param artifactsLocation string = deployment().properties.templateLink.uri
this needs to start with an underscore as in the original template

2022-04-12 20:37 UTC, bmoore-msft commented on demos/vmss-windows-webapp-dsc-autoscale/main.bicep
> +param artifactsLocationSasToken string = ''
this needs to start with an underscore as in the original template

2022-04-13 15:30 UTC, azure-quickstarts commented
@ju-shim - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-13 22:26 UTC, mumian commented
@bmoore-msft - why can't I use the format()function?  The error is "Function'format' found within 'applicationUrl Line: 408, Column: 6".

2022-04-13 22:32 UTC, bmoore-msft commented
because the property name is "url" it expects the uri function instead...

2022-04-14 12:55 UTC, azure-quickstarts commented
@ju-shim - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-06-10 17:04 UTC, azure-quickstarts commented
@ju-shim - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-06-27 16:55 UTC, closed without merging