Adding Bicep template for App Configuration with KV Copy
Azure/azure-quickstart-templates pull request #12290
Opened 2022-03-13 21:43 UTC by willvelida

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-03-13 21:46 UTC, azure-quickstarts commented
@glloyd2010f - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-03-22 21:25 UTC, azure-quickstarts commented
@glloyd2010f - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-03 23:31 UTC, willvelida commented
@bmoore-msft Please review :)

2022-04-08 17:59 UTC, glloyd2010f commented
@willvelida how can I get ahold of you so that I the updates can be added prior to this being merged?

2022-04-10 21:48 UTC, willvelida commented
@glloyd2010f Do you have any email address? You can also ping me on Teams if you like?

2022-04-12 20:20 UTC, bmoore-msft requested changes

2022-04-12 20:20 UTC, bmoore-msft commented on quickstarts/microsoft.appconfiguration/app-configuration-store-kv-copy/main.bicep
> +output KeyVauleReference string = reference(resourceId('Microsoft.AppConfiguration/configurationStores/keyValues', configStoreName, keyData[0].key), '2021-10-01-preview').value
use the bicep syntax for the property references

2022-04-12 20:20 UTC, bmoore-msft commented on quickstarts/microsoft.appconfiguration/app-configuration-store-kv-copy/main.bicep
> +    tags: (contains(item, 'tag') ? item.tag : json('null'))
replace ```json('null')``` with ```null```

2022-04-12 20:20 UTC, bmoore-msft commented on quickstarts/microsoft.appconfiguration/app-configuration-store-kv-copy/main.bicep
> +    contentType: (contains(item, 'contentType') ? item.contentType : json('null'))
replace ```json('null')``` with ```null```

2022-04-12 20:20 UTC, bmoore-msft commented on quickstarts/microsoft.appconfiguration/app-configuration-store-kv-copy/main.bicep
> +resource configStoreNameKeyVaule 'Microsoft.AppConfiguration/configurationStores/keyValues@2021-10-01-preview' = [for item in keyData: {
use the parent syntax for the child resource

2022-04-12 20:20 UTC, bmoore-msft commented on quickstarts/microsoft.appconfiguration/app-configuration-store-kv-copy/main.bicep
> +  dependsOn: [
remove dependsOn when you've added the parent syntax

2022-06-10 17:02 UTC, bmoore-msft commented
Closing abandoned request - please reopen if you can address the feedback.

2022-06-10 17:02 UTC, closed without merging