Azure CLI based DeploymentScript - Importing ACR Images
Azure/azure-quickstart-templates pull request #12333
Opened 2022-03-28 23:13 UTC by Gordonby

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-03-30 14:58 UTC, bmoore-msft requested changes

2022-03-30 14:58 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +param managedIdName string = 'id-ContainerRegistryImport'
move this up to the param section at the top

2022-03-30 14:58 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +  name: guid(roleDefId, depScriptId.id)
add ```acr.id``` to the guid function params

2022-03-30 14:58 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +//@batchSize(1)
remove comment

2022-03-30 14:58 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +param retention string = 'P1D'
remove this and just use a literal value

2022-03-30 14:58 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +param AcrName string
add a defaultValue with ```uniqueString```

2022-03-30 15:14 UTC, Gordonby commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +param RbacRolesNeeded array = [
I like the pattern of providing an array of rbacRoles needed. It doesn't add a great deal to this particular sample, but it makes it easily extensible.

2022-03-30 15:38 UTC, Gordonby commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +param RbacRolesNeeded array = [
Happy to use a var if this is a real problem though 😺

2022-04-11 11:17 UTC, Gordonby commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +resource createAddCertificate 'Microsoft.Resources/deploymentScripts@2020-10-01' = [for image in images: {
Resolving as this sample has pivoted to use the module from the bicep registry

2022-04-11 11:17 UTC, Gordonby commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/main.bicep
> +param RbacRolesNeeded array = [
Resolving as this sample has pivoted to use the module from the bicep registry

2022-04-11 11:18 UTC, Gordonby commented
Pivoted this sample to leverage the module from the Public Bicep Registry
https://github.com/Azure/bicep-registry-modules/pull/65

2022-04-12 21:18 UTC, bmoore-msft requested changes

2022-04-12 21:18 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/README.md
> +This template leverages the Import ACR module from the bicep registry to import public container images into an Azure Container Registry.. A new Azure Container Registry is created.
remove extra period

2022-04-12 21:18 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/README.md
> +The AzureCLI is used in preference to Azure PowerShell primarily to provide a sample of using the Azure CLI DeploymentScripts.
remove this paragraph

2022-04-12 21:18 UTC, bmoore-msft commented on quickstarts/microsoft.resources/deployment-script-azcli-acr-import/README.md
> +See the [Import-ACR] module in the Bicep Registry for more information.
add a link to the module

2022-04-13 22:36 UTC, merged