[IoT Hub] - update resource API versions & create the Bicep file
Azure/azure-quickstart-templates pull request #12354
Opened 2022-04-04 20:34 UTC by mumian

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-04-04 20:38 UTC, azure-quickstarts commented
@robinsh - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-05 14:11 UTC, azure-quickstarts commented
@robinsh - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-08 13:20 UTC, azure-quickstarts commented
@robinsh - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-12 21:44 UTC, bmoore-msft requested changes

2022-04-12 21:44 UTC, bmoore-msft commented on quickstarts/microsoft.devices/iothub-auto-route-messages/main.bicep
> +            connectionString: 'DefaultEndpointsProtocol=https;AccountName=${storageAccountName};EndpointSuffix=${environment().suffixes.storage};AccountKey=${listKeys(storageAccount.id, '2021-02-01')
remove listKeys and use ```storageAccount.listKeys.keys[0].value```

2022-04-13 15:22 UTC, azure-quickstarts commented
@robinsh - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-13 22:35 UTC, merged