Changing Azure Purview to Microsoft Purview
Azure/azure-quickstart-templates pull request #12402
Opened 2022-04-25 20:59 UTC by whhender

Branding update.

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-04-25 21:03 UTC, azure-quickstarts commented
@whhender - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-04-25 23:16 UTC, bmoore-msft requested changes

2022-04-25 23:16 UTC, bmoore-msft commented on quickstarts/microsoft.azurepurview/azure-purview-deployment/README.md
> +# Deploy Mirosoft Purview with Azure Resource Manager (ARM)
fix typo

2022-04-26 14:34 UTC, whhender commented on quickstarts/microsoft.azurepurview/azure-purview-deployment/README.md
> +# Deploy Mirosoft Purview with Azure Resource Manager (ARM)
Fixed

2022-04-26 16:28 UTC, merged