[Signalr] - update api versions and create Bicep file
Azure/azure-quickstart-templates pull request #12463
Opened 2022-05-14 01:03 UTC by mumian

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-05-14 01:07 UTC, azure-quickstarts commented
@juniwang - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-05-14 01:11 UTC, juniwang commented on quickstarts/microsoft.signalrservice/signalr/main.bicep
> +  'Standard_S1'
Thanks so much!  We released a new SKU `Premium_P1`, could you please include it?

2022-05-14 01:11 UTC, juniwang approved these changes

2022-05-16 20:18 UTC, azure-quickstarts commented
@juniwang - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-05-16 21:03 UTC, bmoore-msft requested changes

2022-05-16 21:03 UTC, bmoore-msft commented on quickstarts/microsoft.signalrservice/signalr/main.bicep
> +param enableConnectivityLogs string = 'true'
let use bool as the type for all the true/false params (and remove allowedValues)

2022-05-17 14:28 UTC, azure-quickstarts commented
@juniwang - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-05-17 19:25 UTC, merged