Gm azurewebpubsub bicep
Azure/azure-quickstart-templates pull request #12530
Opened 2022-06-10 23:02 UTC by grminch

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

Initial PR contribution - Quickstart bicep file for Azure Web PubSub service.
*
*
*

2022-06-20 22:38 UTC, grminch commented
@bmoore-msft  this seems to be ready to merge. Is there anything more I need to do?

2022-06-22 17:07 UTC, grminch commented
#sign-off

2022-06-27 22:36 UTC, bmoore-msft requested changes

2022-06-28 21:54 UTC, grminch reviewed
requested changes made, build checks succeeded

2022-07-01 23:20 UTC, merged