[Azure firewall manager virtual hub] - update api versions and create…
Azure/azure-quickstart-templates pull request #12557
Opened 2022-06-24 20:46 UTC by mumian

… bicep

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-06-24 20:49 UTC, azure-quickstarts commented
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-06-27 14:38 UTC, closed without merging

2022-06-27 14:41 UTC, azure-quickstarts commented
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-06-27 20:51 UTC, bmoore-msft requested changes

2022-06-27 20:51 UTC, bmoore-msft commented on quickstarts/microsoft.network/fwm-docs-qs/main.bicep
> +  dependsOn: [
move this above properties

2022-06-27 20:51 UTC, bmoore-msft commented on quickstarts/microsoft.network/fwm-docs-qs/main.bicep
> +  dependsOn: [
move this above properties