update tags for A4Education
Azure/azure-quickstart-templates pull request #12613
Opened 2022-07-12 21:46 UTC by vinnieangel

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-07-12 21:49 UTC, azure-quickstarts commented
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-07-12 22:12 UTC, ecfan requested changes
Hi @vinnieangel, thanks for your contribution. We need to keep the Consumption label to clarify that this template doesn't create a Standard logic app.

2022-07-12 22:15 UTC, ecfan commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
> +  "description": "This template creates an empty logic app that can be used to define workflows.",
A Consumption logic app lets you create only one workflow versus a Standard logic app allows multiple workflows.

```suggestion
  "description": "This template creates an empty Consumption logic app to define a workflow.",
```

2022-07-12 22:15 UTC, ecfan commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
> +    "scenario": "Azure Logic App",
Fix the product name:

```suggestion
    "scenario": "Azure Logic Apps",
```

2022-07-12 22:16 UTC, ecfan requested changes
Please accept the proposed edits, thanks!

2022-07-13 18:36 UTC, azure-quickstarts commented
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-07-13 19:19 UTC, ecfan commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
> +  "description": "This template creates an empty logic app that can be used to define workflows.",
Missed one here.

2022-07-13 23:01 UTC, merged