Adding azure fileshare backup template with hourly backup policy
Azure/azure-quickstart-templates pull request #12681
Opened 2022-07-21 11:28 UTC by kumarisarita5

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Adding azure fileshare backup ARM template with hourly backup policy
* Adding azure fileshare backup bicep template with hourly backup policy

2022-07-25 16:16 UTC, bmoore-msft requested changes
also check the pipeline results for changes that need to be made

2022-07-25 16:16 UTC, bmoore-msft commented on quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly-backup/main.bicep
> +param vaultName string = 'RSVault'
us a globally unique defaultValue with uniqueString()

2022-07-25 16:16 UTC, bmoore-msft commented on quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly-backup/main.bicep
> +  dependsOn: [
move dependsOn above properties

2022-07-25 16:16 UTC, bmoore-msft commented on quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly-backup/main.bicep
> +  dependsOn:[
move dependsOn above properties

2022-07-25 16:16 UTC, bmoore-msft commented on quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly-backup/main.bicep
> +var scheduleRunTimes = [
this doesn't seem to be used to schedule the backup time - only the retention time... is that expected?

2022-07-25 16:16 UTC, bmoore-msft commented on quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly-backup/main.bicep
> +      scheduleRunDays: null
remove null properties

2022-07-25 16:16 UTC, bmoore-msft commented on quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly-backup/metadata.json
> +  "itemDisplayName": "Backup existing File Share using Recovery Services",
there is already a sample in the repo with this metadata

2022-08-02 15:35 UTC, kumarisarita5 commented
Hi @bmoore-msft, without the prereq.azuredeploy.json file the deployment checks are failing, So I've kept this file in the PR.
I've removed the azuredeploy.json and will add it later in new PR.

2022-08-10 10:05 UTC, kumarisarita5 commented
Hi @bmoore-msft, could you please review this PR

2022-08-10 21:13 UTC, merged