update metadata for A4Education
Azure/azure-quickstart-templates pull request #12694
Opened 2022-07-25 21:48 UTC by vinnieangel

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-07-25 21:51 UTC, azure-quickstarts commented
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-07-25 21:59 UTC, ecfan commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
> +                "name": "Azure Logic App",
Official product name is "Azure Logic Apps":

```suggestion
                "name": "Azure Logic Apps",
```

2022-07-25 22:00 UTC, ecfan commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
>      "os": "Linux, Logic App",
```suggestion
    "os": "Linux, Azure Logic Apps",
```

2022-07-25 22:00 UTC, ecfan requested changes
Added feedback, thanks!

2022-07-29 18:54 UTC, ecfan approved these changes
Thank you!

2022-07-29 20:03 UTC, azure-quickstarts commented
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-08-01 18:07 UTC, ecfan commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
> +    "githubUsername": "jeffhollan",
Let's update the owner as Jeff has moved to bigger and better challenges. :)

```suggestion
    "githubUsername": "ecfan",
```

2022-08-01 18:07 UTC, ecfan requested changes
A few more edits, thanks!

2022-08-17 01:20 UTC, ecfan commented
@vinnieangel: Please make the suggested changes to get your PR merged. Otherwise, the system will close the PR after 7 days. Thanks!

2022-08-23 17:52 UTC, ecfan commented
#sign-off

2022-08-23 17:53 UTC, ecfan commented
#sign-off

2022-08-25 15:29 UTC, bmoore-msft requested changes

2022-08-25 15:29 UTC, bmoore-msft commented on quickstarts/microsoft.logic/logic-app-create/metadata.json
>                  "url": "https://azure.microsoft.com/en-us/resources/templates/logic-app-create/"
acom links are being deprecated

2022-08-25 15:32 UTC, azure-quickstarts commented
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-08-26 20:39 UTC, closed without merging