update metadata for A4E
Azure/azure-quickstart-templates pull request #12693
Opened 2022-07-25 21:45 UTC by vinnieangel

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-07-26 16:37 UTC, bmoore-msft requested changes

2022-07-26 16:37 UTC, bmoore-msft commented on quickstarts/microsoft.web/function-app-create-dedicated/metadata.json
> +                "url": "https://azure.microsoft.com/en-us/resources/templates/function-app-create-dedicated/"
https://azure.microsoft.com/en-us/resources/templates/ is being deprecated, you'll want to reference samples here: https://docs.microsoft.com/en-us/samples/browse/?expanded=azure&products=azure-resource-manager

https://docs.microsoft.com/en-us/samples/azure/azure-quickstart-templates/function-app-create-dedicated/

2022-07-29 20:03 UTC, bmoore-msft commented
@vinnieangel - can you resolve the merge conflicts?

2022-07-29 21:48 UTC, vinnieangel commented
@bmoore-msft Thanks for letting me know! I will switch those over. Thanks!

2022-08-01 21:59 UTC, merged