Get started with Azure Data Factory
Azure/azure-quickstart-templates pull request #12793
Opened 2022-08-19 15:16 UTC by jonburchel

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-08-19 19:31 UTC, mumian reviewed
I will send you the Bicep file to be included in this PR.

2022-08-19 19:31 UTC, mumian commented on quickstarts/microsoft.datafactory/data-factory-get-started/README.md
> +
Add the following lines:

![Azure Public Test Date](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/PublicLastTestDate.svg)
![Azure Public Test Result](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/PublicDeployment.svg)

![Azure US Gov Last Test Date](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/FairfaxLastTestDate.svg)
![Azure US Gov Last Test Result](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/FairfaxDeployment.svg)

![Best Practice Check](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/BestPracticeResult.svg)
![Cred Scan Check](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/CredScanResult.svg)

![Bicep Version](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/BicepVersion.svg)

[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2Fquickstarts%2Fmicrosoft.datafactory%2Fdata-factory-get-started%2Fazuredeploy.json)
[![Visualize](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/visualizebutton.svg?sanitize=true)](http://armviz.io/#/?load=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2Fquickstarts%2Fmicrosoft.datafactory%2Fdata-factory-get-started%2Fazuredeploy.json)

2022-08-19 19:31 UTC, mumian commented on quickstarts/microsoft.datafactory/data-factory-get-started/README.md
> +---
Add "-bicep" after "-json".

2022-08-22 18:47 UTC, mumian commented on quickstarts/microsoft.datafactory/data-factory-get-started/README.md
> +
@jonburchel - this one is not copied correctly.  It shall be:

![Azure Public Test Date](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/PublicLastTestDate.svg)
![Azure Public Test Result](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/PublicDeployment.svg)

![Azure US Gov Last Test Date](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/FairfaxLastTestDate.svg)
![Azure US Gov Last Test Result](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/FairfaxDeployment.svg)

![Best Practice Check](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/BestPracticeResult.svg)
![Cred Scan Check](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/CredScanResult.svg)

![Bicep Version](https://azurequickstartsservice.blob.core.windows.net/badges/quickstarts/microsoft.datafactory/data-factory-get-started/BicepVersion.svg)

[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2Fquickstarts%2Fmicrosoft.datafactory%2Fdata-factory-get-started%2Fazuredeploy.json)
[![Visualize](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/visualizebutton.svg?sanitize=true)](http://armviz.io/#/?load=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2Fquickstarts%2Fmicrosoft.datafactory%2Fdata-factory-get-started%2Fazuredeploy.json)

2022-08-23 19:55 UTC, jonburchel commented
@bmoore-msft can you have a look at this build failure.  As far as I can tell the syntax is correct for the location but it isn't passing build.  Thank you!

2022-08-23 20:40 UTC, bmoore-msft requested changes

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/azuredeploy.json
> +{
remove this file - it will be generated in CI

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +var bootstrapRoleAssignmentId_var = guid('${resourceGroup().id}contributor')
rename the var to ```bootstrapRoleAssignmentName``` and use ```guid(resourceGroup().id, managedIdentity.id, roleDefinitionId)``` for the value

You also need to add a variable for:

```bicep
roleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
```

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +    roleDefinitionId: '/subscriptions/${subscription().subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c'
use the ```roleDefinitionId``` variable for the value

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +resource bootstrapRoleAssignmentId 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
downgrade the api version to: ```2022-01-01-preview``` so it works in usgov

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +    azPowerShellVersion: '6.4'
update this to 8.2

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +    scriptContent: 'Invoke-WebRequest -Uri \'https://raw.githubusercontent.com/kromerm/adfdataflowdocs/master/sampledata/moviesDB2.csv\' -OutFile \'moviesDB2.csv\'; $storageAccount = Get-AzStorageAcc
you can't pull content from a private repo - you can add the csv file to this sample or we can stage it

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +  dependsOn: [
move this above properties

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +      connectionString: 'DefaultEndpointsProtocol=https;AccountName=${storageAccountName};AccountKey=${listKeys(storageAccount.id, '2021-09-01').keys[0].value}'
use ```storageAccount.listKeys()``` for the key reference

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +  dependsOn: [
move this above properties

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +  dependsOn: [
move this above properties

2022-08-23 20:40 UTC, bmoore-msft commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +  dependsOn: [
move this above properties

2022-08-23 20:55 UTC, jonburchel commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +  dependsOn: [
Thank you!

2022-08-24 18:01 UTC, jonburchel commented
Thanks for your suggestions @bmoore-msft.  I tried implementing all of them except for moving the file we copy in (still need to do that) but I got new build errors that seem like I got something wrong.  Can you have a look and advise what I need to change still?  Thank you again!

2022-08-24 18:12 UTC, mumian commented on quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
> +roleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
Missing "var". It shall be "var roleDefinitionId ...".

2022-08-24 19:36 UTC, jonburchel commented
@bmoore-msft apologies, but I am still stuck with this.  I tried several variations of changing the location reference but get new errors every time I do.  Also you suggested changes to the azuredeploy.json file but previously advised me not to create this file - that it would be generated for me by the build process.  I have never worked with ARM templates before and normally this is something our devs would do but we cannot find anybody on my team who can help.  Can you review and see what is wrong now?  I've been struggling to get this to publish for a while and not sure what else to try.  Thanks again for your help and sharing your expertise with a newbie!!

2022-08-24 19:48 UTC, jonburchel commented on quickstarts/microsoft.datafactory/data-factory-get-started/azuredeploy.json
> +      "location": "[resourceGroup().location]",
I thought I am not supposed to create this file.  Do I need to update the bicep file someplace similarly?  I tried using parameters("location") where I found it defined there but got an error, so tried location() next and that also failed with an error.

2022-08-25 16:47 UTC, merged