Adding Biceps file and updating Readme file.
Azure/azure-quickstart-templates pull request #12831
Opened 2022-09-07 22:33 UTC by msjasteppe

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added Biceps file.
* Updated Readme file.
*

2022-09-07 22:36 UTC, azure-quickstarts commented
@msjasteppe - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-07 23:31 UTC, azure-quickstarts commented
@msjasteppe - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-07 23:52 UTC, msjasteppe commented
#sign-off

2022-09-08 22:21 UTC, azure-quickstarts commented
@msjasteppe - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-08 22:27 UTC, bmoore-msft requested changes

2022-09-08 22:27 UTC, bmoore-msft commented on quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
> +  name: eventHubFullName
use the `parent` property and remove `dependsOn` below (for all child resources)

2022-09-08 22:27 UTC, bmoore-msft commented on quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
> +  dependsOn: [
remove `dependsOn`

2022-09-08 22:27 UTC, bmoore-msft commented on quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
> +var fhirServiceResourceId = resourceId('Microsoft.HealthcareApis/workspaces/fhirservices', workspaceName, split(fhirServiceName, '/')[1])
use the bicep symbolic reference for your resourceId e.g. `fhirService.id` and remove the vars

2022-09-08 22:27 UTC, bmoore-msft commented on quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
> +  name: guid('${resourceGroup().id}-FhirWriter')
use:
```
name: guid(fhirWriterRoleId, iotConnector.id, fhirService.id)
```

2022-09-08 22:27 UTC, bmoore-msft commented on quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
> +  name: guid('${resourceGroup().id}-EventHubDataReceiver')
use:
```
name: guid(eventHubReceiverRoleId, iotConnector.id, eventHub.id)
```

2022-09-08 22:27 UTC, bmoore-msft commented on quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
> +  dependsOn: [
remove `dependsOn` - you won't need it once you change to symbolic references in the id

2022-09-09 19:07 UTC, azure-quickstarts commented
@msjasteppe - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-09 21:04 UTC, azure-quickstarts commented
@msjasteppe - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-09 21:22 UTC, msjasteppe commented
#sign-off

2022-09-09 21:27 UTC, merged