New Template - Create PIP with DDoS Protection
Azure/azure-quickstart-templates pull request #12886
Opened 2022-09-29 21:37 UTC by mchakka

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-09-29 21:40 UTC, azure-quickstarts commented
@mchakka - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-30 15:25 UTC, azure-quickstarts commented
@mchakka - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-30 15:44 UTC, azure-quickstarts commented
@mchakka - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-09-30 15:55 UTC, azure-quickstarts commented
@mchakka - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-10-04 17:22 UTC, mchakka commented
@bmoore-msft do you mind taking a look at this PR and help merging this if it looks good?

2022-10-04 22:29 UTC, bmoore-msft requested changes

2022-10-04 22:29 UTC, bmoore-msft commented on quickstarts/microsoft.network/pip-with-ddos-ip-protection/main.bicep
> +param name string
add description decorators to all params

2022-10-04 22:29 UTC, bmoore-msft commented on quickstarts/microsoft.network/pip-with-ddos-ip-protection/main.bicep
> +resource name_resource 'Microsoft.Network/publicIPAddresses@2022-05-01' = {
use a descriptive symbolic name, e.g. `publicIp`

2022-10-04 22:29 UTC, bmoore-msft commented on quickstarts/microsoft.network/pip-with-ddos-ip-protection/main.bicep
> +  name: name
use a descriptive param name, e.g. `publicIpName`

2022-10-05 16:09 UTC, azure-quickstarts commented
@mchakka - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-10-05 16:30 UTC, azure-quickstarts commented
@mchakka - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2022-10-06 20:30 UTC, merged