AzureDatabricks-workspace-with-managed-disk-customer-managed-keys
Azure/azure-quickstart-templates pull request #12949
Opened 2022-10-31 16:24 UTC by v-gsapaharam

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2022-11-03 21:04 UTC, v-gsapaharam commented
Greetings Team,  could you please investigate bug# https://github.com/Azure/arm-ttk/issues/713.

2022-11-03 21:07 UTC, v-gsapaharam commented
Hello Brian, could you please investigate the bug# https://github.com/Azure/arm-ttk/issues/713

2022-11-08 21:06 UTC, bmoore-msft requested changes

2022-11-08 21:06 UTC, bmoore-msft commented on quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.json
> +                               "keyVaultUri": "[concat('https://', parameters('keyVaultName'), environment().suffixes.keyvaultDns)]",
```suggestion
                               "keyVaultUri": "[uri(concat('https://', parameters('keyVaultName'), environment().suffixes.keyvaultDns), '/')]",
```

2022-11-08 21:06 UTC, bmoore-msft commented on quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.json
> +               "managedResourceGroupId": "[concat(subscription().id, '/resourceGroups/', variables('managedResourceGroupName'))]",
```suggestion
               "managedResourceGroupId": "[subscriptionResourceId('Microsoft.Resources/resourceGroups', variables('managedResourceGroupName'))]",
```

2022-11-15 22:54 UTC, merged