modified learn link
Azure/azure-quickstart-templates pull request #13203
Opened 2023-02-22 00:45 UTC by vinnieangel

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2023-02-22 00:46 UTC, vinnieangel commented
#sign-off

2023-02-22 00:48 UTC, azure-quickstarts commented
@aahill - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

2023-02-22 19:17 UTC, alex-frankel requested changes

2023-02-22 19:17 UTC, alex-frankel commented on quickstarts/microsoft.cognitiveservices/cognitive-services-universalkey/metadata.json
> +    "learning": "https://learn.microsoft.com/en-us/training/browse/?products=azure&term=cognitive&WT.mc_id=portaledu_inproduct_template&terms=cognitive",
please remove en-us from link so locale can be selected automatically

2023-02-28 18:01 UTC, alex-frankel commented
Closing due to no response

2023-02-28 18:01 UTC, closed without merging