Add new PostgreSQL flexible server template for deployment with VNET …
Azure/azure-quickstart-templates pull request #13429
Opened 2023-06-08 12:47 UTC by ambrahma

…and Data encryption

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2023-06-08 13:52 UTC, pradeepkintali approved these changes

2023-06-08 13:52 UTC, pradeepkintali approved these changes

2023-06-12 18:16 UTC, alex-frankel requested changes

2023-06-12 18:16 UTC, alex-frankel commented on quickstarts/microsoft.dbforpostgresql/flexible-postgresql-with-vnet-dataencryption/main.bicep
> +resource subnet 'subnets@2022-07-01' = {
Deploying subnets as a child resource will cause issues during re-deployment. Instead, create subnets via the `subnets` property in the vnet resource.

2023-06-29 12:46 UTC, closed without merging