Added Bicep file
Azure/azure-quickstart-templates pull request #13800
Opened 2024-02-26 18:32 UTC by v-abdriaz

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2024-02-29 17:15 UTC, mumian commented
@v-abdriaz - this PR contains two templates. Do you still need it?

2024-03-05 16:53 UTC, alex-frankel requested changes

2024-03-05 16:53 UTC, alex-frankel commented on application-workloads/sccm/sccm-currentbranch/main.bicep
> +resource prefix_vmInfo_vmInfo_vmRole_name_vmInfo_siteInfo_clientInfo_vmInfo_siteInfo_clientRole_vmInfo_siteInfo_name_siteInfo_siteRole_vmInfo_name 'Microsoft.Compute/virtualMachines@2019-12-01' = [fo
can we update the resource name to something coherent? it looks like this was autogenerated by the decompiler.

2024-03-05 16:53 UTC, alex-frankel commented on application-workloads/sccm/sccm-currentbranch/main.bicep
> +  name: concat(toLower(prefix), toLower(((i < length(vmInfo)) ? vmInfo[vmrole[i]].name : ((i >= (length(vmInfo) + length(siteInfo))) ? clientInfo[(i - (length(vmInfo) + length(siteInfo)))][clientRole
use idiomatic bicep where possible -- use string interpolation instead of the `concat()` function

2024-04-10 15:26 UTC, closed without merging