Adding Azure Synapse Proof-of-Concept
Azure/azure-quickstart-templates pull request #7863
Opened 2020-07-24 16:55 UTC by JamJarchitect

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2020-08-03 12:08 UTC, JamJarchitect commented
@bmoore-msft Two prerequisites needed for this:
- Supported Synapse region (East US is what I have been testing with) this is available in the documentation.
- AAD User Object ID via scripts folder. 

Please confirm how to get this merged into master.

Kind Regards, James

2020-08-04 23:09 UTC, bmoore-msft commented on 101-synapse-poc/README.md
> +[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%
move this to the top

2020-08-04 23:15 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/pauseroleassignment.json
> +{
this seems identical to the resume template - why do we have both?

2020-08-04 23:18 UTC, bmoore-msft commented on 101-synapse-poc/scripts/getobjectid.ps1
> +    Import-Module AzureAD
Why not just use the Azure cmdlets since a user deploying this template likely already has them installed?

Get-AzAdUser

2020-08-04 23:19 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                "ba92f5b4-2d11-453d-a403-e96b0029c9fe"
if this is the only allowedValue, just move this to a variable...

2020-08-04 23:21 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "defaultValue": "sqladminuser",
remove defaultValue

2020-08-04 23:22 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "defaultValue": "[newGuid()]",
this must be idempotent and unique, and should be a variable (so the user can't break it)

2020-08-04 23:23 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "defaultValue": "[newGuid()]",
if this is for a roleAssignment (as it says in metadata.json) it must be idempotent and unique, and should be a variable (so the user can't break it)

2020-08-04 23:23 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "defaultValue": "[newGuid()]",
if this is for a roleAssignment (as it says in metadata.json) it must be idempotent and unique, and should be a variable (so the user can't break it)

2020-08-04 23:24 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +        "defaultDataLakeStorageAccountUrl": "[concat('https://', variables('dlsName'), '.dfs.core.windows.net')]",
use the environment() function to get core.windows.net

2020-08-04 23:24 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                    "uri": "https://raw.githubusercontent.com/JamJarchitect/azure-quickstart-templates/master/101-synapse-poc/nestedtemplates/pausetemplate.json"
See [BP guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#deployment-artifacts-nested-templates-scripts) for how to handle artifacts

2020-08-04 23:25 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                    "type": "firewallrules"
check the bp guide for sort order of the properties... https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#sort-order-of-properties

2020-08-04 23:26 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                "type": "SystemAssigned"
how is this used?

2020-08-04 23:26 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                    "condition": true,
remove this since it's the default and constant

2020-08-04 23:27 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "dependsOn": [
looks like a lot of the resources have properties in the wrong order, won't comment on them all, be sure to fix according to the BP guide

2020-08-04 23:27 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "condition": true,
as above - remove all of these (won't comment on the rest)

2020-08-04 23:28 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "subscriptionId": "[subscription().subscriptionId]",
remove this property on all nested deployments

2020-08-04 23:28 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +            "resourceGroup": "[resourceGroup().name]",
remove this property on all nested deployments

2020-08-04 23:29 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                "template": {
why is this nested?

2020-08-04 23:30 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                "template": {
why is this nested?

2020-08-04 23:30 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                                "principalType": "User"
what if the user provides the guid for a svc principal?

2020-08-04 23:31 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                                "principalId": "[parameters('userObjectID')]",
if the intent here is that the user deploying is granted access, it's not needed... the user will be the owner of the resource

2020-08-04 23:31 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +        {
remove this since it's never deployed

2020-08-04 23:33 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/pausetemplate.json
> +                "uri": "https://management.azure.com/subscriptions/@{variables('RestAPIVariables')['SubscriptionId']}/resourceGroups/@{variables('RestAPIVariables')['ResourceGroupName']}/providers/Mi
use the environment() function to get the management endpoint

2020-08-04 23:34 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/pausetemplate.json
> +                    "uri": "https://management.azure.com/subscriptions/@{variables('RestAPIVariables')['SubscriptionId']}/resourceGroups/@{variables('RestAPIVariables')['ResourceGroupName']}/provider
use the environment function (won't comment on the rest)

2020-08-06 13:48 UTC, bmoore-msft commented on 101-synapse-poc/scripts/getobjectid.ps1
> +$userUPN = Read-Host -Prompt 'Enter your User Principal Name'
You can get the upn from the context:

(Get-AzAdUser -UserPrincipalName (Get-AzContext).account.id).id

2020-08-17 22:49 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                                "roleDefinitionId": "[concat('/subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Authorization/roleDefinitions/', 'ba92f5b4-2d11-453d-a403-e96b0029
remove concat and use subscriptionResourceId()

2020-08-18 19:50 UTC, JamJarchitect commented on 101-synapse-poc/nestedtemplates/pausetemplate.json
> +    "managementEndpoint": "[environment().authentication.audiences[1]]"
Changes made

2020-08-19 18:47 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +                    "uri": "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-synapse-poc/nestedtemplates/pausetemplate.json"
See [BP guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#deployment-artifacts-nested-templates-scripts) for how to handle nested templates

2020-08-19 18:50 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/logicapproleassignments.json
> +            "defaultValue": "[newGuid()]"
remove defaultValue since this must be passed through - also, this needs to be idempotent otherwise it will fail if redeployed.

2020-08-19 18:50 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/logicapproleassignments.json
> +            "defaultValue": "[newGuid()]"
remove defaultValue

2020-08-24 13:34 UTC, JamJarchitect commented on 101-synapse-poc/azuredeploy.json
> +        "_artifactsLocation": {
SasToken has also been added

2020-08-24 13:35 UTC, JamJarchitect commented on 101-synapse-poc/nestedtemplates/logicapproleassignments.json
> +            "name": "[newGuid()]",
I am now using the guid() function for each of the Pause Logic App and the Resume Logic App

2020-08-24 14:39 UTC, JamJarchitect commented on 101-synapse-poc/azuredeploy.json
> +                "template": {
This is no longer nested

2020-08-24 14:39 UTC, JamJarchitect commented on 101-synapse-poc/azuredeploy.json
> +                    "condition": true,
removed condition

2020-08-24 14:39 UTC, JamJarchitect commented on 101-synapse-poc/azuredeploy.json
> +                "template": {
should be resolved

2020-09-04 19:25 UTC, bmoore-msft commented on 101-synapse-poc/azuredeploy.json
> +        "_artifactsLocation": {
I'm not seeing it in the PR...  also check the pipleine results for changes that are needed here (note the defaultValue)...  You can test this by doing your test deployment using the scripts in the root of the repo (that's how manual validation will be done)

2020-09-04 19:25 UTC, bmoore-msft commented on 101-synapse-poc/README.md
> +[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%
remove this button (you already have it above)

2020-09-04 19:25 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/pauseroleassignment.json
> +{
not sure how this was resolved?

2020-09-04 19:34 UTC, bmoore-msft requested changes

2020-09-04 19:34 UTC, bmoore-msft commented on 101-synapse-poc/nestedtemplates/logicapproleassignments.json
> +            "properties": {
add the principalType property for both roleAssignments

2020-09-07 13:55 UTC, JamJarchitect commented on 101-synapse-poc/README.md
> +[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%
removed

2020-09-07 14:05 UTC, JamJarchitect commented on 101-synapse-poc/nestedtemplates/logicapproleassignments.json
> +            "properties": {
added principalType specifying msi

2020-09-07 14:07 UTC, JamJarchitect commented on 101-synapse-poc/nestedtemplates/pauseroleassignment.json
> +{
i had a separate template for both pause logic app and resume logic app. i have since consolidated these into one template with separate arm templates for their deployments

2020-09-08 13:48 UTC, JamJarchitect commented on 101-synapse-poc/nestedtemplates/logicapproleassignments.json
> +            "properties": {
added principalType specifying ServicePrincipal. msi was not the correct value.

2020-09-08 14:25 UTC, JamJarchitect commented
I have since put guids into the role assignment arm template so that the template can be re-deployed. this i believe has made it idempotent.

2020-09-09 12:42 UTC, JamJarchitect commented
i have since resolved the guid() function for the role assignments.

2020-09-09 15:39 UTC, merged