Azure Cosmos container with multiple containers
Azure/azure-quickstart-templates pull request #8479
Opened 2020-10-30 19:33 UTC by rahulpnath

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2020-11-01 19:40 UTC, bmoore-msft requested changes
See the pipeline results for other changes than need to be made

2020-11-01 19:40 UTC, bmoore-msft commented on 101-cosmosdb-sql-multiple-containers/azuredeploy.json
> +    "accountName": {
add a defaultValue using uniqueString()

2020-11-01 19:40 UTC, bmoore-msft commented on 101-cosmosdb-sql-multiple-containers/azuredeploy.json
> +    "databaseName": {
add a defaultValue

2020-11-02 07:31 UTC, rahulpnath commented
@bmoore-msft Thank you for pointing that out - Fixed them.

2020-11-02 17:55 UTC, merged