ams account create arm template
Azure/azure-quickstart-templates pull request #8545
Opened 2020-11-24 18:44 UTC by IngridAtMicrosoft

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2020-11-24 18:52 UTC, IngridAtMicrosoft commented
#sign-off

2020-11-24 19:06 UTC, mgblythe commented
@bmoore-msft - this one's ready to go

2020-11-24 23:55 UTC, bmoore-msft requested changes
See the pipeline results for the best practice violations that need to be addressed

2020-11-24 23:55 UTC, bmoore-msft commented on 101-media-services-account-create/README.md
> +<a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fazure%2Fazure-quickstart-templates%2Fmaster%2F101-media-services-create%2Fazuredeploy.json"
See the contribution guide or other doc samples for how to construct a proper README.md for the repo

2020-11-24 23:55 UTC, bmoore-msft commented on 101-media-services-account-create/azuredeploy.json
> +    "mediaServiceName": {
add a defaultValue using uniqueString()

2020-11-24 23:55 UTC, bmoore-msft commented on 101-media-services-account-create/metadata.json
> +{
add the $schema property

2021-01-04 15:28 UTC, bmoore-msft commented
Closing abandoned request - please reopen if you can address the feedback.

2021-01-04 15:28 UTC, closed without merging

2021-01-04 15:42 UTC, mgblythe commented
@mumian as FYI

2021-01-04 15:59 UTC, mumian commented
@IngridAtMicrosoft @mgblythe  -  there is an existing quickstart template - 101-media-services-create.  I have another PR refreshing the template - https://github.com/Azure/azure-quickstart-templates/pull/8627.

2021-01-05 20:32 UTC, IngridAtMicrosoft commented
> @IngridAtMicrosoft @mgblythe - there is an existing quickstart template - 101-media-services-create. I have another PR refreshing the template - #8627.
@mumian That is a different ARM template created by a customer.  I am supplying two others.  Although this one is similar, it is the one from Microsoft and Media Servicess.

2021-01-05 21:58 UTC, mumian commented
@IngridAtMicrosoft Azure Quickstart templates is a community contributed repository. The two templates are very similar. Both create a storage account resource and a media service resource.  We should update the existing template instead of creating a new one.