Deploying Cloud Services (extended support)
Azure/azure-quickstart-templates pull request #8684
Opened 2021-01-20 21:09 UTC by gauravchandwani1

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-01-20 21:41 UTC, mimckitt commented
Following @mimckitt

2021-01-20 21:46 UTC, gauravchandwani1 commented
Create cloud service (extended support

2021-01-20 21:46 UTC, gauravchandwani1 commented
Closed by mistake.

2021-01-21 15:52 UTC, bmoore-msft requested changes

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +      "type": "string",
add a defaultValue using  uniqueString() - also mention in the description that this must be globally unique

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +    "location": {
Add defaultValue - see: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#parameters

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +    "deploymentLabel": {
add defaultValue

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +    "packageSasUri": {
See [BP guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#deployment-artifacts-nested-templates-scripts) for how to handle artifacts

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +      "type": "array",
add a defaultValue

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +    "cloudServiceName": "[parameters('cloudServiceName')]",
remove this and just use the parameter directly

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +    "resourcePrefix": "[concat('/subscriptions/', variables('subscriptionID'), '/resourceGroups/', resourceGroup().name, '/providers/')]"
remove this, you will need to use the resourceId function for resourceIds

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +        "[concat('Microsoft.Network/virtualNetworks/', parameters('vnetName'))]",
remove concat() and use resourceId

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +              "id": "[concat(variables('resourcePrefix'), 'Microsoft.Network/loadBalancers/', variables('lbName'))]",
remove concat() and use resourceId()

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.json
> +                        "id": "[concat(variables('resourcePrefix'), 'Microsoft.Network/publicIPAddresses/', parameters('publicIPName'))]"
remove concat() and use resourceId()

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.parameters.json
> +    "cloudServiceName": {
remove the parameters that have defaultValues

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/azuredeploy.parameters.json
> +    "rdpPublicConfig": {
for the config (and private config) - move the XML to a variable in the file and prompt for username and password as the param values.  Can also remove the \r\n

Asking the user to supply XML within JSON will be prone to failure.

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/metadata.json
> +  "summary": "This template allows deploying a Cloud Services (extended support) with mulitple roles. It also creates virtual network, public ip address.",
This template deploys an Azure Cloud Service (extended support) with multiple roles. It also creates a virtual network and public ip address.

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/readme.md
> +# Cloud Services (extended support) template
change the casing on the filename to: README.md

Also see the pipeline results for the proper links

2021-01-21 15:52 UTC, bmoore-msft commented on 101-cses-multi-role-rdp/readme.md
> +This template allows to create cloud service (extended support) and also creates associated resources (virtual network, public IP address).
This template deploys an Azure Cloud Service (extended support) with multiple roles. It also creates a virtual network and public ip address.

2021-03-15 14:12 UTC, bmoore-msft commented
Closing abandoned request - please reopen if you can address the feedback.

2021-03-15 14:12 UTC, closed without merging

2021-03-15 14:53 UTC, gauravchandwani1 commented
Surbhi - Please look into this.

On Mon, Mar 15, 2021, 19:43 Brian Moore ***@***.***> wrote:

> Closed #8684
> <https://github.com/Azure/azure-quickstart-templates/pull/8684>.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/azure-quickstart-templates/pull/8684#event-4458972972>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APSGCIJJZZCJFS6RW2WQCP3TDYIXXANCNFSM4WLIYAJA>
> .
>

2021-03-31 09:20 UTC, gachandw commented
#sign-off