Add sample: Front Door Standard/Premium (Preview) with Azure Functions origin
Azure/azure-quickstart-templates pull request #8805
Opened 2021-02-28 20:59 UTC by johndowns

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add sample - Front Door Standard/Premium (Preview) with Azure Functions origin

2021-03-01 18:11 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-03-02 07:07 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-03-02 07:57 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-03-03 22:45 UTC, bmoore-msft requested changes

2021-03-03 22:45 UTC, bmoore-msft commented on 201-front-door-standard-premium-function-public/readme.md
> +# Front Door Standard/Premium (Preview) with Azure Functions origin
change casing on filename

2021-03-03 23:04 UTC, johndowns commented on 201-front-door-standard-premium-function-public/readme.md
> +# Front Door Standard/Premium (Preview) with Azure Functions origin
Done.

2021-03-03 23:07 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-03-03 23:34 UTC, merged