Creating an ARM template for Cosmos DB SQL data plane RBAC
Azure/azure-quickstart-templates pull request #8908
Opened 2021-03-18 19:39 UTC by nichatur

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-03-19 14:29 UTC, bmoore-msft requested changes

2021-03-19 14:29 UTC, bmoore-msft commented on 101-cosmosdb-sql-rbac/azuredeploy.json
> +    "accountName": {
add a defaultValue with uniqueString

2021-03-19 14:29 UTC, bmoore-msft commented on 101-cosmosdb-sql-rbac/azuredeploy.json
> +      "defaultValue": "[newGuid()]",
this must be idempotent

2021-03-19 14:29 UTC, bmoore-msft commented on 101-cosmosdb-sql-rbac/azuredeploy.json
> +      "defaultValue": "[newGuid()]",
this must be idempotent

2021-03-19 14:29 UTC, bmoore-msft commented on 101-cosmosdb-sql-rbac/azuredeploy.parameters.json
> +        "location": {
remove this and use the defaultValue in the template

2021-03-20 10:14 UTC, nichatur commented
Hi @bmoore-msft , Thanks for much for your latest commit! 
I do have one worry however, if a customer uses this ARM template for regular deployment and decides to update the "dataActions", will this not lead to the creation of a new Role Definition instead of simply updating the existing one?

Especially because we no longer provide the ability to the customer to specify this ID via a parameter to ensure it stays consistent across deployments.

2021-03-22 14:54 UTC, bmoore-msft commented
If a roleDefinition (or roleAssignment) is created with the same properties and a different name/guid - the PUT will fail, so using a random guild will eventually block deployment.

2021-03-22 14:54 UTC, merged