Add sample: Front Door Premium (Preview) with Web Application Firewall and Microsoft-managed rule sets
Azure/azure-quickstart-templates pull request #8962
Opened 2021-04-13 23:26 UTC by johndowns

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add sample: Front Door Premium (Preview) with Web Application Firewall and Microsoft-managed rule sets

2021-04-13 23:30 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-13 23:58 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-14 00:33 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-14 00:45 UTC, bmoore-msft commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-15 15:36 UTC, bmoore-msft requested changes

2021-04-15 15:36 UTC, bmoore-msft commented on 201-front-door-premium-waf-managed/README.md
> +[![Visualize](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/visualizebutton.svg?sanitize=true)](http://armviz.io/#/?load=https%3A%2F%2Fraw.gith
remove extraneous button

2021-04-15 18:53 UTC, johndowns commented on 201-front-door-premium-waf-managed/README.md
> +[![Visualize](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/visualizebutton.svg?sanitize=true)](http://armviz.io/#/?load=https%3A%2F%2Fraw.gith
Fixed.

2021-04-15 18:56 UTC, azure-quickstarts commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-15 19:18 UTC, azure-quickstarts commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-15 20:08 UTC, azure-quickstarts commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-15 20:19 UTC, azure-quickstarts commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-15 20:29 UTC, azure-quickstarts commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-15 20:37 UTC, azure-quickstarts commented
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

2021-04-16 04:22 UTC, johndowns commented
@bmoore-msft Any other changes required for this one?

2021-04-16 18:08 UTC, merged