update api-version, add bicep support
Azure/azure-quickstart-templates pull request #9433
Opened 2021-05-01 02:53 UTC by markjbrown

## Changelog

* update api-version
* add bicep support

2021-06-08 22:28 UTC, bmoore-msft requested changes
is the bicep file meant to be empty?

2021-06-10 20:07 UTC, bmoore-msft requested changes

2021-06-10 20:07 UTC, bmoore-msft commented on quickstarts/microsoft.documentdb/cosmosdb-table-autoscale/main.bicep
> +  name: '${tableName}'
use

```name: tableName```

2021-06-11 00:00 UTC, markjbrown commented on quickstarts/microsoft.documentdb/cosmosdb-table-autoscale/main.bicep
> +  name: '${tableName}'
fixed.

2021-06-14 17:26 UTC, merged