FIX_TEMPLATE: 201-dependency-between-scripts-using-extensions
Azure/azure-quickstart-templates pull request #9442
Opened 2021-05-01 14:04 UTC by javid-spektra

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-05-05 17:49 UTC, bmoore-msft requested changes

2021-05-05 17:49 UTC, bmoore-msft commented on 201-dependency-between-scripts-using-extensions/azuredeploy.json
> +    "mongoconfigureubuntu": "[concat(parameters('_artifactsLocation'), 'scripts/', 'mongo-configure-ubuntu.sh', parameters('_artifactsLocationSasToken'))]",
use the uri() to create the uris

2021-05-06 19:55 UTC, javid-spektra commented on 201-dependency-between-scripts-using-extensions/azuredeploy.json
> +    "mongoconfigureubuntu": "[concat(parameters('_artifactsLocation'), 'scripts/', 'mongo-configure-ubuntu.sh', parameters('_artifactsLocationSasToken'))]",
Done

2021-05-17 14:11 UTC, javid-spektra commented on 201-dependency-between-scripts-using-extensions/azuredeploy.json
> +    "_artifactsLocation": {
Done

2021-05-26 13:51 UTC, merged